// Code generated by mockery v2.24.0. DO NOT EDIT.

package mocks

import (
	models "GophKeeper/internal/models"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Storage is an autogenerated mock type for the storage type
type Storage struct {
	mock.Mock
}

type Storage_Expecter struct {
	mock *mock.Mock
}

func (_m *Storage) EXPECT() *Storage_Expecter {
	return &Storage_Expecter{mock: &_m.Mock}
}

// CardCreate provides a mock function with given fields: ctx, c, userID
func (_m *Storage) CardCreate(ctx context.Context, c models.Card, userID int) error {
	ret := _m.Called(ctx, c, userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Card, int) error); ok {
		r0 = rf(ctx, c, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storage_CardCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CardCreate'
type Storage_CardCreate_Call struct {
	*mock.Call
}

// CardCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - c models.Card
//   - userID int
func (_e *Storage_Expecter) CardCreate(ctx interface{}, c interface{}, userID interface{}) *Storage_CardCreate_Call {
	return &Storage_CardCreate_Call{Call: _e.mock.On("CardCreate", ctx, c, userID)}
}

func (_c *Storage_CardCreate_Call) Run(run func(ctx context.Context, c models.Card, userID int)) *Storage_CardCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.Card), args[2].(int))
	})
	return _c
}

func (_c *Storage_CardCreate_Call) Return(_a0 error) *Storage_CardCreate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_CardCreate_Call) RunAndReturn(run func(context.Context, models.Card, int) error) *Storage_CardCreate_Call {
	_c.Call.Return(run)
	return _c
}

// CardDelete provides a mock function with given fields: ctx, id, userID
func (_m *Storage) CardDelete(ctx context.Context, id int, userID int) error {
	ret := _m.Called(ctx, id, userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storage_CardDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CardDelete'
type Storage_CardDelete_Call struct {
	*mock.Call
}

// CardDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - userID int
func (_e *Storage_Expecter) CardDelete(ctx interface{}, id interface{}, userID interface{}) *Storage_CardDelete_Call {
	return &Storage_CardDelete_Call{Call: _e.mock.On("CardDelete", ctx, id, userID)}
}

func (_c *Storage_CardDelete_Call) Run(run func(ctx context.Context, id int, userID int)) *Storage_CardDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *Storage_CardDelete_Call) Return(_a0 error) *Storage_CardDelete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_CardDelete_Call) RunAndReturn(run func(context.Context, int, int) error) *Storage_CardDelete_Call {
	_c.Call.Return(run)
	return _c
}

// CardUpdate provides a mock function with given fields: ctx, c, userID
func (_m *Storage) CardUpdate(ctx context.Context, c models.Card, userID int) error {
	ret := _m.Called(ctx, c, userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Card, int) error); ok {
		r0 = rf(ctx, c, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storage_CardUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CardUpdate'
type Storage_CardUpdate_Call struct {
	*mock.Call
}

// CardUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - c models.Card
//   - userID int
func (_e *Storage_Expecter) CardUpdate(ctx interface{}, c interface{}, userID interface{}) *Storage_CardUpdate_Call {
	return &Storage_CardUpdate_Call{Call: _e.mock.On("CardUpdate", ctx, c, userID)}
}

func (_c *Storage_CardUpdate_Call) Run(run func(ctx context.Context, c models.Card, userID int)) *Storage_CardUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.Card), args[2].(int))
	})
	return _c
}

func (_c *Storage_CardUpdate_Call) Return(_a0 error) *Storage_CardUpdate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_CardUpdate_Call) RunAndReturn(run func(context.Context, models.Card, int) error) *Storage_CardUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// Cards provides a mock function with given fields: ctx, userID
func (_m *Storage) Cards(ctx context.Context, userID int) ([]models.Card, error) {
	ret := _m.Called(ctx, userID)

	var r0 []models.Card
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]models.Card, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []models.Card); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Card)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Storage_Cards_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cards'
type Storage_Cards_Call struct {
	*mock.Call
}

// Cards is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *Storage_Expecter) Cards(ctx interface{}, userID interface{}) *Storage_Cards_Call {
	return &Storage_Cards_Call{Call: _e.mock.On("Cards", ctx, userID)}
}

func (_c *Storage_Cards_Call) Run(run func(ctx context.Context, userID int)) *Storage_Cards_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *Storage_Cards_Call) Return(_a0 []models.Card, _a1 error) *Storage_Cards_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Storage_Cards_Call) RunAndReturn(run func(context.Context, int) ([]models.Card, error)) *Storage_Cards_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewStorage interface {
	mock.TestingT
	Cleanup(func())
}

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewStorage(t mockConstructorTestingTNewStorage) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
