CREATE TABLE notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- уникальный идентификатор заметки
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE, -- идентификатор пользователя
    title TEXT NOT NULL, -- заголовок заметки
    body TEXT, -- тело заметки
    expiration_at TIMESTAMP WITH TIME ZONE, -- дата истечения срока действия заметки
    created_at TIMESTAMP WITH TIME ZONE, -- отметка времени создания заметки
    updated_at TIMESTAMP WITH TIME ZONE -- отметка времени обновления заметки
)