CREATE TABLE cards(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- уникальный идентификатор карты
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE, -- идентификатор пользователя
    name TEXT NOT NULL, -- название записи
    number TEXT NOT NULL, -- номер карты
    cvc TEXT NOT NULL, -- защитный код карты
    exp_month INT NOT NULL, -- месяц истечения срока действия карты
    exp_year INT NOT NULL, -- год истечения срока действия карты
    created_at TIMESTAMP WITH TIME ZONE, -- отметка времени создания записи
    updated_at TIMESTAMP WITH TIME ZONE -- отметка времени обновления записи
)