CREATE TABLE sessions (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- идентификатор сессии
    user_id                     INT REFERENCES users(id) ON DELETE CASCADE, -- идентификатор пользователя
    refresh_token               UUID NOT NULL, -- refresh_token для обновления access_token
    mac_address                 TEXT, -- mac-адрес пользователя
    ip_address                  INET, -- ip адрес пользователя
    refresh_token_expired_at    BIGINT NOT NULL, -- время жизни refresh_token
    public_key                  TEXT, -- публичный ключ клиента
    created_at                  TIMESTAMP WITH TIME ZONE, -- время создания сессии
    updated_at                  TIMESTAMP WITH TIME ZONE -- время обновления сессии
);
