CREATE TABLE media(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- уникальный идентификатор записи
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE, -- идентификатор пользователя
    title TEXT NOT NULL, -- название данных
    body BYTEA NOT NULL, -- данные записи
    media_type TEXT NOT NULL,
    note TEXT, -- заметка к записи
    expiration_at TIMESTAMP WITH TIME ZONE, -- дата истечения срока действия записи
    created_at TIMESTAMP WITH TIME ZONE, -- отметка времени создания записи
    updated_at TIMESTAMP WITH TIME ZONE -- отметка времени обновления записи
)