package postgres

import (
	"context"
	"errors"
	"fmt"

	"GophKeeper/internal/models"
	"GophKeeper/internal/repository"

	"github.com/jackc/pgx/v5"
)

type Storage struct {
	repo *repository.Repo
}

func NewMediaStorage(r *repository.Repo) *Storage {
	return &Storage{repo: r}
}

func (s *Storage) MediaCreate(ctx context.Context, m models.Media, userID int) error {
	q := `INSERT INTO media(user_id, title, body, media_type, expiration_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)`

	_, err := s.repo.Pool.Exec(ctx, q, userID,
		m.Title, m.Body, m.MediaType, m.ExpiredAt, m.CreatedAt, m.UpdatedAt)
	if err != nil {
		return fmt.Errorf("media create in repo: %w", err)
	}

	return nil
}

func (s *Storage) MediaUpdate(ctx context.Context, m models.Media, userID int) error {
	q := `UPDATE media SET(title, body, media_type, expiration_at, updated_at)
= ($1, $2, $3, $4, $5) WHERE id = $6 AND user_id = $7`

	tag, err := s.repo.Pool.Exec(ctx, q,
		m.Title, m.Body, m.MediaType, m.ExpiredAt, m.UpdatedAt, m.ID, userID)
	if err != nil {
		return fmt.Errorf("media update in repo: %w", err)
	}

	if tag.RowsAffected() == 0 {
		return fmt.Errorf("media update in repo: %w", models.ErrNotFound)
	}

	return nil
}

func (s *Storage) MediaDelete(ctx context.Context, id, userID int) error {
	q := `DELETE FROM media WHERE id = $1 AND user_id = $2`

	tag, err := s.repo.Pool.Exec(ctx, q, id, userID)
	if err != nil {
		return fmt.Errorf("delete media from repo: %w", err)
	}

	if tag.RowsAffected() == 0 {
		return fmt.Errorf("delete media from repo: %w", models.ErrNotFound)
	}

	return nil
}

func (s *Storage) Medias(ctx context.Context, userID int) ([]models.Media, error) {
	q := `SELECT id, title, body, media_type, expiration_at, created_at, updated_at 
FROM media WHERE user_id = $1`

	rows, err := s.repo.Pool.Query(ctx, q, userID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, models.ErrNotFound
		}

		return nil, fmt.Errorf("get media from repo: %w", err)
	}

	defer rows.Close()

	medias := make([]models.Media, 0)

	for rows.Next() {
		m := models.Media{}

		err = rows.Scan(
			&m.ID,
			&m.Title,
			&m.Body,
			&m.MediaType,
			&m.ExpiredAt,
			&m.CreatedAt,
			&m.UpdatedAt)
		if err != nil {
			return nil, fmt.Errorf("get media from repo: %w", err)
		}

		medias = append(medias, m)
	}

	return medias, nil
}

/*
CREATE TABLE media(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- уникальный идентификатор записи
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE, -- идентификатор пользователя
    title TEXT NOT NULL, -- название данных
    body BYTEA NOT NULL, -- данные записи
    media_type TEXT NOT NULL,
    expiration_at TIMESTAMP WITH TIME ZONE, -- дата истечения срока действия записи
    created_at TIMESTAMP WITH TIME ZONE, -- отметка времени создания записи
    updated_at TIMESTAMP WITH TIME ZONE -- отметка времени обновления записи
)*/
