// Code generated by mockery v2.24.0. DO NOT EDIT.

package mocks

import (
	models "GophKeeper/internal/models"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Storage is an autogenerated mock type for the storage type
type Storage struct {
	mock.Mock
}

type Storage_Expecter struct {
	mock *mock.Mock
}

func (_m *Storage) EXPECT() *Storage_Expecter {
	return &Storage_Expecter{mock: &_m.Mock}
}

// PasswordCreate provides a mock function with given fields: ctx, pass, userID
func (_m *Storage) PasswordCreate(ctx context.Context, pass models.Password, userID int) error {
	ret := _m.Called(ctx, pass, userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Password, int) error); ok {
		r0 = rf(ctx, pass, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storage_PasswordCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PasswordCreate'
type Storage_PasswordCreate_Call struct {
	*mock.Call
}

// PasswordCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - pass models.Password
//   - userID int
func (_e *Storage_Expecter) PasswordCreate(ctx interface{}, pass interface{}, userID interface{}) *Storage_PasswordCreate_Call {
	return &Storage_PasswordCreate_Call{Call: _e.mock.On("PasswordCreate", ctx, pass, userID)}
}

func (_c *Storage_PasswordCreate_Call) Run(run func(ctx context.Context, pass models.Password, userID int)) *Storage_PasswordCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.Password), args[2].(int))
	})
	return _c
}

func (_c *Storage_PasswordCreate_Call) Return(_a0 error) *Storage_PasswordCreate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_PasswordCreate_Call) RunAndReturn(run func(context.Context, models.Password, int) error) *Storage_PasswordCreate_Call {
	_c.Call.Return(run)
	return _c
}

// PasswordDelete provides a mock function with given fields: ctx, id, userID
func (_m *Storage) PasswordDelete(ctx context.Context, id int, userID int) error {
	ret := _m.Called(ctx, id, userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storage_PasswordDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PasswordDelete'
type Storage_PasswordDelete_Call struct {
	*mock.Call
}

// PasswordDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - userID int
func (_e *Storage_Expecter) PasswordDelete(ctx interface{}, id interface{}, userID interface{}) *Storage_PasswordDelete_Call {
	return &Storage_PasswordDelete_Call{Call: _e.mock.On("PasswordDelete", ctx, id, userID)}
}

func (_c *Storage_PasswordDelete_Call) Run(run func(ctx context.Context, id int, userID int)) *Storage_PasswordDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *Storage_PasswordDelete_Call) Return(_a0 error) *Storage_PasswordDelete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_PasswordDelete_Call) RunAndReturn(run func(context.Context, int, int) error) *Storage_PasswordDelete_Call {
	_c.Call.Return(run)
	return _c
}

// PasswordUpdate provides a mock function with given fields: ctx, pass, userID
func (_m *Storage) PasswordUpdate(ctx context.Context, pass models.Password, userID int) error {
	ret := _m.Called(ctx, pass, userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Password, int) error); ok {
		r0 = rf(ctx, pass, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storage_PasswordUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PasswordUpdate'
type Storage_PasswordUpdate_Call struct {
	*mock.Call
}

// PasswordUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - pass models.Password
//   - userID int
func (_e *Storage_Expecter) PasswordUpdate(ctx interface{}, pass interface{}, userID interface{}) *Storage_PasswordUpdate_Call {
	return &Storage_PasswordUpdate_Call{Call: _e.mock.On("PasswordUpdate", ctx, pass, userID)}
}

func (_c *Storage_PasswordUpdate_Call) Run(run func(ctx context.Context, pass models.Password, userID int)) *Storage_PasswordUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.Password), args[2].(int))
	})
	return _c
}

func (_c *Storage_PasswordUpdate_Call) Return(_a0 error) *Storage_PasswordUpdate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_PasswordUpdate_Call) RunAndReturn(run func(context.Context, models.Password, int) error) *Storage_PasswordUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// Passwords provides a mock function with given fields: ctx, userID
func (_m *Storage) Passwords(ctx context.Context, userID int) ([]models.Password, error) {
	ret := _m.Called(ctx, userID)

	var r0 []models.Password
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]models.Password, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []models.Password); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Password)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Storage_Passwords_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Passwords'
type Storage_Passwords_Call struct {
	*mock.Call
}

// Passwords is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *Storage_Expecter) Passwords(ctx interface{}, userID interface{}) *Storage_Passwords_Call {
	return &Storage_Passwords_Call{Call: _e.mock.On("Passwords", ctx, userID)}
}

func (_c *Storage_Passwords_Call) Run(run func(ctx context.Context, userID int)) *Storage_Passwords_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *Storage_Passwords_Call) Return(_a0 []models.Password, _a1 error) *Storage_Passwords_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Storage_Passwords_Call) RunAndReturn(run func(context.Context, int) ([]models.Password, error)) *Storage_Passwords_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewStorage interface {
	mock.TestingT
	Cleanup(func())
}

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewStorage(t mockConstructorTestingTNewStorage) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
