openapi: 3.0.3

info:
  title: GophKeeper
  description: Сервис хранения паролей и других данных
  version: 1.0.0

tags:
  - name: api
    description: Service API

paths:
  /register:
    $ref: './v1/register/register_paths.yaml'
  /login:
    $ref: './v1/login/login_paths.yaml'
  /passwords:
    $ref: './v1/passwords/passwords_paths.yaml'
  /passwords/{passwordID}:
    $ref: './v1/passwords/passwords_paths_with_id.yaml'
  /cards:
    $ref: './v1/cards/cards_paths.yaml'
  /cards/{cardID}:
    $ref: './v1/cards/cards_paths_with_id.yaml'
  /notes:
    $ref: './v1/notes/notes_paths.yaml'
  /notes/{noteID}:
    $ref: './v1/notes/notes_paths_with_id.yaml'
  /medias:
    $ref: './v1/medias/media_paths.yaml'
  /medias/{mediaID}:
    $ref: './v1/medias/media_paths_with_id.yaml'
  /key:
    $ref: './v1/key/key_path.yaml'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: "JWT"
      description: "JWT authorization header using the Bearer scheme"